
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:latest
        env:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
    env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/musicbrainz_db
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@v2
        with:
          tool: sqlx-cli
      - name: SQLx setup
        run: sqlx db setup
      - name: Formatting
        uses: clechasseur/rs-cargo@v2
        with:
          command: fmt
          args: --check
        continue-on-error: true
      - name: Cargo Check
        uses: clechasseur/rs-cargo@v2
        with:
          command: check
          args: --all-targets --all-features --locked
        continue-on-error: true
      - name: Linting
        uses: clechasseur/rs-cargo@v2
        with:
          command: clippy
          args: --all-targets --all-features --locked -- -D warnings
        continue-on-error: true
      - name: Tests
        run: |
          cargo test
